// Layout обертка над приложением для нескольких разделов приложения если внутри  папки app то это обертка над всем приложением

// import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import toast, { Toaster } from 'react-hot-toast'; 
// библиотека тоестер для уведомлений компанент <Toaster /> нужно сделать глобальным на все приложение удобней тут в главном лояуте но он рендерится на сервере
// а библиотека на клиенте Toaster это как провайдер в редакстулкит добавляем его в body и оно применяется ко всему приложению

import './globals.css';
// import { Header } from '@/components/shared/header';

const nunito = Nunito({
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
});

// в галвном лаяуте не должно быть мета

// export const metadata: Metadata = {
//   title: 'Next Pizza | Главная',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
            <link data-rh="true" rel="icon" href="/logo.png" />
        </head>
      <body className={nunito.variable}>
          {children}
          <Toaster />
      </body>
    </html>
  );
}
